version: '3'

networks:
    devops:
        driver: bridge

services:
    mysql:
        image: mysql:5.7.29
        container_name: mysql
        restart: unless-stopped
        tty: true
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes: 
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: devops
            MYSQL_USER: devops
            MYSQL_PASSWORD: docker
            MYSQL_ROOT_PASSWORD: docker
        networks: 
            - devops
    
    backend:
        build: ./backend
        container_name: backend
        user: 1000:1000
        ports: 
            - 3000:3000
        networks: 
            - devops
        depends_on: 
            - mysql
    
    frontend:
        build: ./frontend
        container_name: frontend
        user: 1000:1000
        ports:
            - 5000:5000
        networks: 
            - devops
        depends_on: 
            - backend